version: 0.2

env:
  variables:
    BUILD_DIR: build/libs

phases:
  install:
    commands:
      - echo "Using CodeBuild image with JDK 17"
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - ./gradlew clean build -x test
      - test -d ${BUILD_DIR} || (echo "Build dir not found"; exit 1)

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - deploy/**/*
    - ${BUILD_DIR}/*.jar