version: 0.2

phases:
  pre_build:
    commands:
      - echo "[buildspec] pre_build"
      - chmod +x gradlew || true
  build:
    commands:
      - echo "[buildspec] build"
      - ./gradlew clean build -x test
      - test -d build/libs || (echo "build/libs not found" && exit 1)
      # 산출된 JAR을 app.jar로 복사 (최상단)
      - cp build/libs/*.jar app.jar

  post_build:
    commands:
      - echo "[buildspec] post_build done"

artifacts:
  files:
    - app.jar
    - appspec.yml
    - scripts/**/*