version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "[INSTALL] Java runtime set to Corretto 17"

  pre_build:
    commands:
      - echo "[PRE_BUILD] Make executables"
      - chmod +x gradlew || true
      - find scripts -type f -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true
      - chmod +x scripts/*.sh || true
  build:
    commands:
      - echo "[BUILD] Gradle build"
      - ./gradlew clean build -x test
      - echo "[BUILD] Locate jar"
      - JAR=$(ls -1 build/libs/*.jar | head -n1); echo "JAR=$JAR"; test -f "$JAR"
      - cp "$JAR" app.jar
      - ls -al app.jar

  post_build:
    commands:
      - echo "[POST_BUILD] Done"

artifacts:
  files:
    - appspec.yml
    - app.jar
    - scripts/**/*
  discard-paths: yes